language: csharp
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
mono:
  - 4.0.5
os:
  - linux
  - osx
osx_image: xcode7.1
branches:
  only:
    - master
    - release
    - dev
    - /^(.*\/)?ci-.*$/
script:
  - ./build.sh --quiet verify
notifications:
  webhooks:
    secure: "wQWIB0w+JTMEcME/A3EkbE/kOEd2Ir6JLouu8GnKxpAYkkfgZTJvB39vDZlddcUX2KUIh1wEb+pymSYdVuY8IqgnOiafyNHMr+hOOmyijgGGDEgwFhc6kVg9QE9in1W6EhFc3Zc4q1lTTX8lI3y/fxv4ry4D6UDs7ddcDpBvpWk="
  on_success: always
  on_failure: always
  on_start: always