language: csharp
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - libunwind8
before_install:
  - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install nginx; fi
install:
  - curl -sSL http://nginx.org/download/nginx-1.8.0.tar.gz | tar zxfv - -C /tmp && cd /tmp/nginx-1.8.0/
  - ./configure --prefix=$HOME/nginxinstall --with-http_ssl_module
  - make
  - make install
  - export PATH="$PATH:$HOME/nginxinstall/sbin/"
  - cd $OLDPWD
mono:
  - 4.0.5
os:
  - linux
  - osx
osx_image: xcode7.1
branches:
  only:
    - master
    - release
    - dev
    - /^(.*\/)?ci-.*$/
script:
  - ./build.sh --quiet verify

